import {
  Laptop,
  Megaphone,
  Palette,
  Scissors,
  Shirt,
  PenTool,
  Camera,
  Film,
  GraduationCap,
  Users,
  Heart,
  UtensilsCrossed,
  House as Home,
  Package,
  Calendar,
  Wrench,
  Rocket,
  Briefcase,
  Plane,
  PawPrint,
  Car,
  Dumbbell,
  Scale,
  type LucideIcon,
} from 'lucide-react'

export const CATEGORIES = [
  'IT & Technology',
  'Marketing & Social Media',
  'Makeup Artist',
  'Beauty & Salon',
  'Fashion & Clothing',
  'Writers & Content Creators',
  'Photography',
  'Videography & Film',
  'Education & Tutors',
  'Coaching & Consulting',
  'Health & Wellness',
  'Fitness & Sports',
  'Food & Catering',
  'Travel & Tourism',
  'Home Services',
  'Pets & Animal Care',
  'Automotive & Repair',
  'Handmade & Crafts',
  'Events & Planning',
  'Local Services',
  'Legal & Financial',
  'Startups',
  'Freelancers',
] as const

export type Category = typeof CATEGORIES[number]

export const CATEGORY_ICONS: Record<string, LucideIcon> = {
  'IT & Technology': Laptop,
  'Marketing & Social Media': Megaphone,
  'Makeup Artist': Palette,
  'Beauty & Salon': Scissors,
  'Fashion & Clothing': Shirt,
  'Writers & Content Creators': PenTool,
  'Photography': Camera,
  'Videography & Film': Film,
  'Education & Tutors': GraduationCap,
  'Coaching & Consulting': Users,
  'Health & Wellness': Heart,
  'Fitness & Sports': Dumbbell,
  'Food & Catering': UtensilsCrossed,
  'Travel & Tourism': Plane,
  'Home Services': Home,
  'Pets & Animal Care': PawPrint,
  'Automotive & Repair': Car,
  'Handmade & Crafts': Package,
  'Events & Planning': Calendar,
  'Local Services': Wrench,
  'Legal & Financial': Scale,
  'Startups': Rocket,
  'Freelancers': Briefcase,
}

export const DEFAULT_CATEGORY_ICON = Briefcase

// Optional persona illustrations. Drop PNGs into public/categories/<file>
// matching these paths and they'll show as circular avatars on the
// Categories page. Categories without files (or with files that 404)
// are silently skipped — no broken images.
export const CATEGORY_ILLUSTRATIONS: Record<string, string> = {
  'IT & Technology': '/categories/it-technology.png',
  'Marketing & Social Media': '/categories/marketing-social-media.png',
  'Makeup Artist': '/categories/makeup-artist.png',
  'Beauty & Salon': '/categories/beauty-salon.png',
  'Fashion & Clothing': '/categories/fashion-clothing.png',
  'Writers & Content Creators': '/categories/writers-content.png',
  'Photography': '/categories/photography.png',
  'Videography & Film': '/categories/video.png',
  'Fitness & Sports': '/categories/fitness-sports.png',
  'Travel & Tourism': '/categories/travel-tourism.png',
  'Pets & Animal Care': '/categories/pets-animal-care.png',
  'Automotive & Repair': '/categories/automotive-repair.png',
  'Legal & Financial': '/categories/legal-financial.png',
  'Education & Tutors': '/categories/education-tutors.png',
  'Coaching & Consulting': '/categories/coaching-consulting.png',
  'Health & Wellness': '/categories/health-wellness.png',
  'Food & Catering': '/categories/food-catering.png',
  'Home Services': '/categories/home-services.png',
  'Handmade & Crafts': '/categories/handmade-crafts.png',
  'Events & Planning': '/categories/events-planning.png',
  'Local Services': '/categories/local-services.png',
  'Startups': '/categories/startups.png',
  'Freelancers': '/categories/freelancers.png',
}

export const CATEGORY_ACCENTS: Record<string, { bg: string; fg: string; grad: [string, string] }> = {
  'Food & Catering':     { bg: '#FEF3E8', fg: '#C2410C', grad: ['#FEF3E8', '#FDE8D3'] },
  'Beauty & Salon':      { bg: '#FDF4FF', fg: '#9333EA', grad: ['#FDF4FF', '#F3E8FF'] },
  'Makeup Artist':       { bg: '#FDF4FF', fg: '#9333EA', grad: ['#FDF4FF', '#FAE8FF'] },
  'Home Services':       { bg: '#F0FDF4', fg: '#16A34A', grad: ['#F0FDF4', '#DCFCE7'] },
  'Local Services':      { bg: '#F0FDF4', fg: '#16A34A', grad: ['#F0FDF4', '#DCFCE7'] },
  'Fashion & Clothing':  { bg: '#EFF6FF', fg: '#2563EB', grad: ['#EFF6FF', '#DBEAFE'] },
  'IT & Technology':     { bg: '#F0FDFA', fg: '#0F766E', grad: ['#F0FDFA', '#CCFBF1'] },
  'Events & Planning':   { bg: '#FFFBEB', fg: '#D97706', grad: ['#FFFBEB', '#FEF3C7'] },
  'Health & Wellness':   { bg: '#FFF1F2', fg: '#E11D48', grad: ['#FFF1F2', '#FFE4E6'] },
  'Education & Tutors':  { bg: '#F5F3FF', fg: '#7C3AED', grad: ['#F5F3FF', '#EDE9FE'] },
  'Coaching & Consulting': { bg: '#F5F3FF', fg: '#7C3AED', grad: ['#F5F3FF', '#EDE9FE'] },
  'Photography':         { bg: '#ECFEFF', fg: '#0891B2', grad: ['#ECFEFF', '#CFFAFE'] },
  'Videography & Film':  { bg: '#FEF2F2', fg: '#B91C1C', grad: ['#FEF2F2', '#FECACA'] },
  'Writers & Content Creators': { bg: '#F0F9FF', fg: '#0369A1', grad: ['#F0F9FF', '#E0F2FE'] },
  'Marketing & Social Media':   { bg: '#FFF7ED', fg: '#EA580C', grad: ['#FFF7ED', '#FFEDD5'] },
  'Handmade & Crafts':   { bg: '#FEFCE8', fg: '#CA8A04', grad: ['#FEFCE8', '#FEF9C3'] },
  'Startups':            { bg: '#EEF2FF', fg: '#4F46E5', grad: ['#EEF2FF', '#E0E7FF'] },
  'Freelancers':         { bg: '#F8FAFC', fg: '#475569', grad: ['#F8FAFC', '#F1F5F9'] },
  'Fitness & Sports':    { bg: '#F7FEE7', fg: '#65A30D', grad: ['#F7FEE7', '#ECFCCB'] },
  'Travel & Tourism':    { bg: '#E0F2FE', fg: '#0EA5E9', grad: ['#E0F2FE', '#BAE6FD'] },
  'Pets & Animal Care':  { bg: '#FEF3C7', fg: '#92400E', grad: ['#FEF3C7', '#FDE68A'] },
  'Automotive & Repair': { bg: '#F5F5F4', fg: '#44403C', grad: ['#F5F5F4', '#E7E5E4'] },
  'Legal & Financial':   { bg: '#E0E7FF', fg: '#3730A3', grad: ['#E0E7FF', '#C7D2FE'] },
}

export const DEFAULT_CATEGORY_ACCENT = { bg: '#FEF3E8', fg: '#C2410C', grad: ['#FEF3E8', '#FDE8D3'] as [string, string] }
